[theme]
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF" 
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
maxUploadSize = 200
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = true
toolbarMode = "minimal"

[ui]
hideTopBar = false
hideSidebarNav = false
