
# .streamlit/secrets.toml
# Replace with your actual Supabase credentials

SUPABASE_URL = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvaG1lZ3JkaGhiZ3ByZnZ2a3FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDk5MjEsImV4cCI6MjA3MDc4NTkyMX0.90Oq-t7HP-T3FGM-8q9WVvTaDeIYmBYR86M9hTdMLl0"
SUPABASE_ANON_KEY = "https://tohmegrdhhbgprfvvkqp.supabase.co"

# Example:
# SUPABASE_URL = "https://abcdefghij.supabase.co" 
# SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
