
# .streamlit/secrets.toml
# Replace with your actual Supabase credentials

api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvaG1lZ3JkaGhiZ3ByZnZ2a3FwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTIwOTkyMSwiZXhwIjoyMDcwNzg1OTIxfQ.WfWt1IJaYPxnVQWghbR7I-MUN7aXjefibg3v3_Nbl9U"
database_url  = "https://tohmegrdhhbgprfvvkqp.supabase.co"

# Example:
# SUPABASE_URL = "https://abcdefghij.supabase.co" 
# SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
